### ISSUE TITLE
ModelAlias support

### ISSUE THREAD

**Issue by daritter** [scikit-hep/decaylanguage#100] opened 2020-06-02 16:52 UTC
Hi,

it seems our latest decay file is no longer compatible with decaylanguage as we now have ModelAlias lines in our main decay file to define some aliases for models. For example

```
ModelAlias SLBKPOLE_Dtoetaplnu SLBKPOLE 1.0 0.281 1.0 2.010;
```
Supporting the ModelAlias itself is obviously easy enough but then also supporting it to be used as models in the decay files seems currently a bit non-trivial.

**Comment by eduardo-rodrigues** [comment] 2020-06-02 17:05
Hi @daritter, it's actually rather easy to deal with a so-far unknown decay model on the fly, see the section "advanced usage" I had at some point added to the README. This being said, it's just nicer to continue expanding the known models as they get created. But you folks at Belle have enhanced the master decay file with something new? OK, then we will need some info for the parser …

BTW, it would then be great to update your master decay file at `https://github.com/scikit-hep/decaylanguage/tree/master/decaylanguage/data` for the benefit of everyone.

**Comment by daritter** [comment] 2020-06-02 17:21
I've seen the README but that was still talking about a fixed list of models, now it seems people on my side started to use a dynamic list of models. And I'm quite sure it's actually not a new feature as we're stuck on a rather old evtgen for the time being so this is something which evtgen has supported for quite some time now :D

As a matter of fact looking in the `EvtGenBase/EvtDecayTable.cpp` there seem to be a few other things supported that decaylanguage doesn't do:

* Define
* ModelAlias
* PythiaAliasParam
* PythiaGenericParam
* Particle
* ChangeMassMin
* ChangeMassMax
* IncludeBirthFactor
* IncludeDecayFactor
* CopyDecay
* RemoveDecay
...

At least some of these are obviously a bad idea to have (Particle (re-)definition in the decay file seems like a recipe for unpleasantness to me) and I'm not demanding that you support all of that. But the ModelAlias actually sounds like a good idea. I've also seen the Change*Mass in one signal decay file of ours but there I'm more inclined on pushing this out of the decay file.

Don't get me wrong, I'm really happy with the effort of decaylanguage. I am mostly making issues so that this is documented. Problem with giving you our decayfile always the same: we haven't managed to get our software licensed yet so I have to ... dance around that

**Comment by eduardo-rodrigues** [comment] 2020-06-02 22:15
Thanks very much @daritter for bringing this to our attention. I confess that I had not looked at that EvtGen file, being happily parsing LHCb decay files and the one we have from Belle right now in the repository. Clearly it would have been a good thing to do :D.

Note that `Define` is actually supported since the beginning. But not the others on your list. I also noticed that EvtGen has `noPhotos` and `normalPhotos` as well as `yesPhotos`, and only the latter is known to `DecayLanguage`.

> Don't get me wrong, I'm really happy with the effort of decaylanguage. I am mostly making issues so that this is documented. Problem with giving you our decayfile always the same: we haven't managed to get our software licensed yet so I have to ... dance around that

I don't. It's *excellent* that you provide us with feedback and suggestions! That's super appreciated and I only regret that we get too little feedback - "am happy" is also welcome :-).

If software licensing is an issue you could maybe provide a few example lines related to the enhancements you need, as that should be enough to test code for the new functionality to support? Of course, if somebody commits a PR, even better!

**Comment by eduardo-rodrigues** [comment] 2020-11-02 17:07
Hi @daritter, I hope you're doing well!

Listen, shall we try and get back to this issue/task? Let me re-state that "If software licensing is an issue you could maybe provide a few example lines related to the enhancements you need, as that should be enough to test code for the new functionality to support? Of course, if somebody commits a PR, even better!".
This is true for the required developments for introducing `ModelAlias` and the other missing keywords into the list of known keywords to the parser.

**Comment by eduardo-rodrigues** [comment] 2020-11-04 23:25
Hi @ch2ohch2oh, as a Belle person would you have input to this discussion? Anyone else you may think of that has interest in decay files and would chime in?

**Comment by eduardo-rodrigues** [comment] 2020-11-05 11:49
For (my) reference - here are some examples of `ModelAlias` usage in decay files that I could find online in public repositories:
```
#
# Model alias for the D -> omega l nu
# MV=2.0 GeV and MA1=MA2=2.4 GeV, R2=0.6, RV=1.5
#
ModelAlias SLPOLE_Dtoomegalnu SLPOLE 1.00 -0.605 0.0 1.0
                                     0.60 -0.605 0.0 1.0
                                     1.50 -0.871 0.0 1.0
                                     0.00 -0.605 0.0 1.0;
#
# Model aliases for D -> Klnu, pilenu, etalnu, eta'lnu
#
ModelAlias SLBKPOLE_DtoKlnu SLBKPOLE 1.0 0.25 1.0 2.112;
ModelAlias SLBKPOLE_Dtopilnu SLBKPOLE 1.0 0.25 1.0 2.010;
ModelAlias SLBKPOLE_Dtoetalnu SLBKPOLE 1.0 0.25 1.0 2.010;
ModelAlias SLBKPOLE_Dtoetaplnu SLBKPOLE 1.0 0.25 1.0 2.010;
```

**Comment by eduardo-rodrigues** [comment] 2020-11-05 15:18
Hi @klieret, allow me to ping you as well as I believe you're also working on Belle II? (Just remembered this when you reported earlier today at the HSF coordination meeting.)

**Comment by klieret** [comment] 2020-11-14 12:09
Hi @eduardo-rodrigues I don't think I'm familiar enough with decay files to give direct input here. But what I could do is write a quick email to some mailing lists.

Can you be a bit more specific about the input that you're looking for (so that I can be more precise in the email)? 

Do I understand you correctly that you are inclined to implement `ModelAlias` and the main issue is to have more example lines available for testing? 

As software licensing remains an issue for Belle II, what one option would be to ask someone to manually check out `decaylanguage` and run it over the Belle II decay file and then report any errors. Would that be of any help to you?

For the email: Is there something like a quick pitch of `decaylanguage` that I could use to get people interested?

**Comment by klieret** [comment] 2020-11-14 12:12
Actually, regarding licensing, it looks like there are exactly 8 authors with commits associated to `DECAY_BELLE2.DEC`, so perhaps we could get green light from them before we figure out the software licensing as a whole.

**Comment by eduardo-rodrigues** [comment] 2020-11-16 14:27
Hi @klieret, thanks a lot for your response.

> Hi @eduardo-rodrigues I don't think I'm familiar enough with decay files to give direct input here. But what I could do is write a quick email to some mailing lists.

Sounds great. That would be appreciated. For sure I know that some people in Belle(II) use this package, hence enhancements should be welcome.

> Could you be a bit more specific about the input that you're looking for (so that I can be more precise in the email)?

So, as you can see from @daritter's messages above, he got in touch because the latest and greatest Belle II master decay file contains some keywords and hence bits of descriptions that are not supported in `DecayLanguage`. That's because I have never seen such bits of code in decay files ;-). Some, also, are rather rare and/or old keywords in EvtGen ... I am of course interested in making the package more useful, hence the need to see at least bits of decay files with what is not yet supported ... @daritter was also suggesting  that himself and some of your colleagues might be interested in contributing with code, and that would be even better! 
 
> Do I understand you correctly that you are inclined to implement ModelAlias and that the main issue is to have more example lines available for testing?

Precisely. But again, if the enhacement comes via a PR from a user, that will be really cool.

> As software licensing remains an issue for Belle II, what one option would be to ask someone to manually check out decaylanguage and run it over the Belle II decay file and then report any errors. Would that be of any help to you?

This would help a bit but would not tell me what exact syntax to support. Indeed, the Lark parser needs a grammar (see https://github.com/scikit-hep/decaylanguage/blob/master/decaylanguage/data/decfile.lark), and that can only be written with the examples of what to support.

> For the email: Is there something like a quick pitch of decaylanguage that I could use to get people interested?

Well, decay files are used by just about anyone doing Flavour Physics, right :-)? This package parses decay files, provides classes to define and play with decay chains, makes it trivial to make nice DOT plots from parsed decay chains, etc. There is more that can be done, and that's also on the horizon ...

Still on licensing - you folks really need to get your code licensed ;-). We went through the exercise for LHCb some years ago and it's a real plus when collaborating with anyone.
Your master decay file may contain only 8 authors but strictly speaking is the property of Belle II. What might be OK is to get a PR here with your master file and get the approval from your computing/software coordinator explicit in there. To be that seems enough for now to be able to expose the file in this package (releases). Or else, as said above, just provide bits of decay files where the missing functionality is used.

Thank you very much for any help here!

**Comment by daritter** [comment] 2020-11-16 17:38
Sorry for the tardiness.

Yes, I would want to get some momentum for this in Belle 2 but sadly so far that didn't go anywhere and at the moment I have exactly zero time left to chip in personally so it's slow and tedious.

The licensing is being worked on and hopeful optimists aim for February to get it finally done. It's not only our master decay file, the smaller signal decay files are the ones using "interesting" features and it's distributed a bit across files.

I know I don't have any time this or next week but I will try my best to cobble together a representative example after that ... or find someone to do it.

**Comment by eduardo-rodrigues** [comment] 2020-11-16 17:48
Thanks @daritter. Understood and understandable.

Aside what you say I think @klieret's help is in any case great, as a way to potentially engage more/better.

**Comment by eduardo-rodrigues** [comment] 2020-12-11 09:39
Any news/update on this front, @daritter and/or @klieret?

**Comment by klieret** [comment] 2020-12-22 16:47
Hi @eduardo-rodrigues  I just wrote an email to everyone with commits regarding dec files. I hope that someone finds their way here. If not, I will try to target specific people to get things moving.   Sorry for being so late with the reply, wish you happy holidays!

**Comment by eoxford** [comment] 2021-01-04 15:54
Hi @eduardo-rodrigues et al. - I'm the one who introduced the ModelAlias lines in question to the decay file, so I thought I should probably comment. (Sorry it took so long!) I am not an expert in any of this though, and I confess I don't really understand what the issue is here or what we're trying to do. I know the decfile works as intended with the ModelAlias lines (I've used it in signal decfiles before as well with no issue). We are not the first people to use ModelAlias - I know the BESIII collaboration uses this feature as well, but I'm not sure if they use this scikit-hep package.

If it's a question of testing, it should be very easy to create a file that uses more ModelAlias lines (although, why do we need more?), but all ModelAlias does is redirect to a specified EvtGen model, so again I'm not sure what we're trying to test. Sorry for my ignorance about this, and sorry it took me so long to comment.

**Comment by eduardo-rodrigues** [comment] 2021-01-07 17:54
Thanks very much for getting in touch, @eoxford.

> I know the decfile works as intended with the ModelAlias lines (I've used it in signal decfiles before as well with no issue).

I have no doubt! The main point of this thread is to get examples for the package to be extended to be able to understand ModelAlias statements with some real-life examples. I believe you use single- and multiple-line ModelAlias statements in your decfiles.

> We are not the first people to use ModelAlias - I know the BESIII collaboration uses this feature as well, but I'm not sure if they use this scikit-hep package. If it's a question of testing, it should be very easy to create a file that uses more ModelAlias lines (although, why do we need more?), but all ModelAlias does is redirect to a specified EvtGen model, so again I'm not sure what we're trying to test.

Indeed I need test files to provide 100% coverage. You can ssee above a discussion about licensing issues, so I cannot get right now the full master decfile. But I believe it should be no problem to have 1-N trival files just for testing the functionality. Can you provide that?

So not, it's not a matter of needing more simply because so far we have none to test the ModelAlias statements.

Have you got other doubts? If you poke around a bit you will see that the grammar to parse dec files is done in this pure Python package via the Lark package. Nothing is aware of EvtGen.

**Comment by eduardo-rodrigues** [comment] 2021-01-07 17:58
BTW, if you have an example using `RemoveDecay` that would also be welcome, so that I make the package deal with it.

Thanks!

**Comment by eoxford** [comment] 2021-01-13 21:35
Hi @eduardo-rodrigues, sorry for my delayed response (again). I could certainly give you example decfiles that use ModelAlias. Do you want 1 file that uses every ModelAlias in the master decfile, or do you want separate files for each ModelAlias? Or both?

**Comment by eduardo-rodrigues** [comment] 2021-01-13 21:43
No worries, we all know too well what being swamped with work means.

One big file with all use cases is great. I will then see if I need to split it for the tests.

Advance thanks!

**Comment by eoxford** [comment] 2021-01-13 21:59
Can do. I'll email it to you. (I would post it here, but I'm not sure if it's okay to post pieces of our master decfile on a public forum, and better safe than sorry.) Also, unfortunately I don't have any examples with `RemoveDecay` - is that used in our decfile? I don't recall seeing it before.

**Comment by eduardo-rodrigues** [comment] 2021-01-14 08:05
Thanks a lot.

As far as I know none of us uses `RemoveDecay` in decfiles, but @daritter drew a list of keywords he could find on EvtGen and I am happy to make those known to `DecayLanguage`, just in case. Of course that's only useful if *somebody* still uses those keywords, and that's where I need feedback. I implemented `CopyDecay` already (was easy) but have no example for `RemoveDecay` (relevant largely in combination with `CopyDecay`). If Belle-II does not use this then don't worry.

**Comment by GiacomoXT** [comment] 2021-07-14 09:01
Hi @eduardo-rodrigues ,

let me come back to this: basf2 is now public. In case you still need our main decay file, you can find it here: https://github.com/belle2/basf2/blob/main/decfiles/dec/DECAY_BELLE2.DEC

**Comment by eduardo-rodrigues** [comment] 2021-07-14 12:54
> Hi @eduardo-rodrigues ,
> 
> let me come back to this: basf2 is now public. In case you still need our main decay file, you can find it here: https://github.com/belle2/basf2/blob/main/decfiles/dec/DECAY_BELLE2.DEC

That's excellent to know. Many thanks @GiacomoXT.

While at it, let me update you all on this issue - I did try and deal with ModelAlias but it is far less trivial than I had originally thought it would be. It will require a proper update of the Lark parsing we presently do. I'm not finding time for this task. Since this is so far only used by Belle II, would anyone of you (or a colleague) be interested in tackling the update? That would be a really cool and welcome contribution from the community!

**Comment by GiacomoXT** [comment] 2021-07-22 13:34
@eduardo-rodrigues today, during an internal meeting, I pointed some MC production experts to this repository to see if I engage some interested persons. I can't promise anything, but in case there will be some follow-ups (even for just using this package), I will try to push the persons for taking care of this. 😛

**Comment by eduardo-rodrigues** [comment] 2021-07-24 21:01
> @eduardo-rodrigues today, during an internal meeting, I pointed some MC production experts to this repository to see if I engage some interested persons. I can't promise anything, but in case there will be some follow-ups (even for just using this package), I will try to push the persons for taking care of this. 😛

Thank you for that! Fingers crossed.

**Comment by eduardo-rodrigues** [comment] 2022-11-04 13:01
Closed via https://github.com/scikit-hep/decaylanguage/pull/270.

**Closed by eduardo-rodrigues** 2022-11-04 13:01 UTC
Labels: enhancement
